### ISSUE TITLE
`test_examples.py` seem to fail due to import error

### ISSUE THREAD

**Issue by arseniiv** [drhagen/parsita#14]
I’m probably doing something wrong but when I run `pytest .` in the main directory, all tests pass except all the ones in `test_examples.py` due to
```
ModuleNotFoundError: No module named 'examples'
```
(the same error in all three cases). I’m a bit confused, maybe I should run tests in some other way.

**Comment by arseniiv** [comment]
Yeah it seems I did it the wrong way. I uninstalled parsita from all python installations, then made
```
py -m pip install -e .
py -m pytest .
```
and now it all works like a charm, though there are two warnings about unknown `pytest.mark.timeout`.

Though VS Code still does seem concerned with those three tests, but it seems using its own `pytest` and in an obscure way. But maybe you’d be interested it doesn’t work in there (but works completely okay via the explicit `pytest .`).

**Comment by drhagen** [comment]
I typically run pytest through tox with the command [`python -m pytest --cov "src/parsita"`](https://github.com/drhagen/parsita/blob/master/tox.ini#L20). This works because python adds the working directory to the path, so that `examples` becomes a module on the path, which is something that pytest does not do when run as a console script. This is probably not ideal, but I am not sure of a better setup. I don't want to install the examples or move them to the tests folder or stop testing the examples at all.

The warning about unknown `pytest.mark.timeout` may happen if the `pytest-timeout` package is not installed.

**Comment by arseniiv** [comment]
Ah, I should have checked the requirements and install the thing properly. Thanks!
