### ISSUE TITLE
parsing failure with alternative `opt()`s

### ISSUE THREAD

**Issue by jay-h-cunningham** [drhagen/parsita#18]
This is a silly example, but I would have expected the following to parse "week", "year", or "":

```python
class SimpleParser(TextParsers):
    weeks = opt(lit("week", "wk", "w")) > constant("week")
    years = opt(lit("year", "yr", "y")) > constant("year")

    value = weeks | years

SimpleParser.value.parse("")
# => Success('week')

SimpleParser.value.parse("week")
# => Success('week')

SimpleParser.value.parse("year")
# Failure("Expected 'week' or 'wk' or 'w' or end of source but found 'year'\nLine 1, character 1\n\nyear\n^   ")
```

**Comment by drhagen** [comment]
This is an unfortunate but fundamental limitation of recursive descent parsers, which is what Parsita is based on. I don't want to get into parsing theory, but basic problem of recursive descent parsers is that whenever you are parsing something of the form `weeks | years`, then if `weeks` succeeds, then `years` is never tried. Even if parsing fails later on, the parser does not go back and try an alternative to a successful match to see if that will get farther. In your case, `weeks` succeeds with `""`, so `value` succeeds, so then Parsita checks if the whole input was consumed. This "end of source" check fails so a `Failure` is returned without seeing if the original successful `weeks` match was the problem.

A good rule of thumb is that you should never put an `opt` on the left side of a `|`. Because `opt` always succeeds, the right side can never be tried. You probably already know this, but you can rewrite it as (assuming you want `"week"` to be the default):

```
class SimpleParser(TextParsers):
    weeks = lit("week", "wk", "w") > constant("week")
    years = lit("year", "yr", "y") > constant("year")

    value = weeks | years | success("week")
```

or

```
class SimpleParser(TextParsers):
    weeks = opt(lit("week", "wk", "w")) > constant("week")
    years = lit("year", "yr", "y") > constant("year")

    value = years | weeks
```

To make your original parser do what you expect, I would have to replace the internal recursive descent machinery with a packrat parser. It is something I would like to investigate, but it is a big undertaking for which I have yet to start.

**Comment by jay-h-cunningham** [comment]
Interesting, thank you for the succinct explanation of what's going on. Yeah, I only hit this limitation because I was doing something stupid, so I really don't have any burning need to replicate the expected behavior.

Thanks! This is a really nice library and I appreciate you making it available.
